
#spring.datasource.url=jdbc:postgresql://localhost:5432/id_idea
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl=create
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database=postgresql
#spring.jpa.show-sql=false
#spring.datasource.hikari.maximum-pool-size=5
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:products
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    schemas: migration
    group: true
    out-of-order: true

